const projects = [
  {
    index: 1,
    id: "eda",
    title: "Exploratory Data Analysis",
    summary: "Comprehensive data analysis to identify optimal location for a new Mediterranean restaurant.",
    description:
      "Conducted comprehensive data analysis on various datasets, analyzing over 100,000 data points to identify optimal location for a new Mediterranean restaurant.",
    services: ["Design", "Development"],
    builtOn: ["Nextjs", "Firebase", "ChakraUI"],
    imgSrc: "/mockups/savingspree/savingspree_mockup.jpeg",
    imageGallery: [
      "/mockups/savingspree/savingspree1.png",
      "/mockups/savingspree/savingspree2.png",
      "/mockups/savingspree/savingspree3.png",
      "/mockups/savingspree/savingspree4.png",
    ],
    siteUrl: "https://github.com/RandilW/ECEN-360-501/tree/main/Assignments/Assignment%201",
    featured: true,
  },
  {
    index: 2,
    id: "profmatch",
    title: "ProfMatch",
    summary: "A platform for personalized professor recommendations based on student preferences.",
    description:
      "Marriage template is a fully customizable website where you can showcase your wedding information",
    services: ["Design", "Development"],
    builtOn: ["Nextjs", "Framer Motion"],
    imgSrc: "/mockups/marriage-template/marriage-template-mockup.png",
    imageGallery: [
      "/mockups/marriage-template/marriage-template1.png",
      "/mockups/marriage-template/marriage-template2.png",
      "/mockups/marriage-template/marriage-template3.png",
    ],
    siteUrl: "https://marriage-template.netlify.app",
    featured: true,
  },
  {
    index: 3,
    id: "airbnb-clone",
    title: "Airbnb Clone",
    summary: "Generate beautiful color shades.",
    services: ["Development"],
    builtOn: ["Nextjs", "ChakraUI"],
    description:
      "Shades Generator is a webapp which generates beautiful color shades for your designs.",
    imgSrc: "/mockups/shades-generator/shades-generator_mockup.jpeg",
    imageGallery: [
      "/mockups/shades-generator/shades-generator1.png",
      "/mockups/shades-generator/shades-generator2.png",
      "/mockups/shades-generator/shades-generator3.png",
    ],
    siteUrl: "https://shades-generator.vercel.app",
  },
  {
    index: 4,
    id: "todo",
    title: "ToDo",
    summary: "A place where people & lawyers meet each other",
    description:
        "Mr.Lawyer is a consultancy, where people meet experienced lawyer near them & lawyers can connect to their clients.",
    services: ["Design", "Development"],
    builtOn: ["HTML", "CSS", "Javascript"],
    imgSrc: "/mockups/todo/todo_mockup.png",
    imageGallery: [
      "/mockups/mr-lawyer/mr-lawyer1.png",
      "/mockups/mr-lawyer/mr-lawyer2.png",
      "/mockups/mr-lawyer/mr-lawyer3.png",
      "/mockups/mr-lawyer/mr-lawyer4.png",
    ],
    siteUrl: "https://mrlawyerfirm.web.app/",
    featured: false,
  },
  {
    index: 5,
    id: "client-design-project",
    title: "Client Design Project",
    summary: "Custom web design & development for a tailoring brand.",
    description:
      "Avis Tailors is a tailoring brand. They focus on providing well tailored clothes, the website and design is reflection of those attributes.",
    services: ["Design", "Development"],
    builtOn: ["TailwindCSS", "HTML"],
    imgSrc: "/mockups/avis-tailors/avistailors_mockup.jpeg",
    imageGallery: [
      "/mockups/avis-tailors/avis-tailors1.png",
      "/mockups/avis-tailors/avis-tailors2.png",
      "/mockups/avis-tailors/avis-tailors3.png",
    ],
    siteUrl: "https://avistailors.netlify.com",
    featured: true,
  },
  {
    index: 6,
    id: "aggiefunds",
    title: "AggieFunds",
    summary: "A place where people & lawyers meet each other",
    description:
      "Mr.Lawyer is a consultancy, where people meet experienced lawyer near them & lawyers can connect to their clients.",
    services: ["Design", "Development"],
    builtOn: ["HTML", "CSS", "Javascript"],
    imgSrc: "/mockups/mr-lawyer/mrlawyer_mockup.jpeg",
    imageGallery: [
      "/mockups/mr-lawyer/mr-lawyer1.png",
      "/mockups/mr-lawyer/mr-lawyer2.png",
      "/mockups/mr-lawyer/mr-lawyer3.png",
      "/mockups/mr-lawyer/mr-lawyer4.png",
    ],
    siteUrl: "https://mrlawyerfirm.web.app/",
    featured: true,
  },
  {
    index: 7,
    id: "revtube",
    title: "RevTube",
    summary: "A place where people & lawyers meet each other",
    description:
        "Mr.Lawyer is a consultancy, where people meet experienced lawyer near them & lawyers can connect to their clients.",
    services: ["Design", "Development"],
    builtOn: ["HTML", "CSS", "Javascript"],
    imgSrc: "/mockups/revtube/revtube_mockup.png",
    imageGallery: [
      "/mockups/mr-lawyer/mr-lawyer1.png",
      "/mockups/mr-lawyer/mr-lawyer2.png",
      "/mockups/mr-lawyer/mr-lawyer3.png",
      "/mockups/mr-lawyer/mr-lawyer4.png",
    ],
    siteUrl: "https://mrlawyerfirm.web.app/",
    featured: false,
  },
];

export default projects;
